# Messages formatting API: https://docs.advntr.dev/minimessage/format.html
# For disable message, leave quotes empty

options:
  min_length: 3
  max_length: 16

messages:

  # Config reloaded
  reloaded: "<#78ff9e>[✔] Конфиг перезагружен"
  few_arguments: "<#ff0051>[❌] Недостаточно аргументов."
  no_permissions: "<#ff0051>[❌] Недостаточно прав."
  unknown_argument: "<#ff0051>[❌] Неизвестный аргумент."
  player_not_found: "<#ff0051>[❌] Игрок <white>[%PLAYER%] не найден."
  invalid_symbols: "<#ff0051>[❌] Недопустимые символы в имени."
  confirm_registration: "<white>Вы выбрали: <#78beff><bold>%TEMP_FIO%</bold><white>, вы уверены?<newline>Напишите <#78ff9e>[Да] <white>или <#ff0051>[Нет]<white>."
  cancel_choose: "<#ff0051>[❌] Вы отменили выбор имени, выберите новое."
  successful_fio_change: "<#78ff9e>[✔] Фамилия и имя игрока изменены."
  too_short: "<#ff0051>[❌] Слишком короткое имя или фамилия."
  too_long: "<#ff0051>[❌] Слишком длинное имя или фамилия."


  # Registration title and subtitle
  register:
    title: "<#ff0051>[⌚] Укажите имя и фамилию"
    subtitle: "<white>иᴍя ȹᴀмилия"

  # Login title and subtitle
  registered:
    title: "<#78ff9e>[✔] Успешная регистрация."
    subtitle: "<white>Удачной игры, <#78beff><bold>%mfio_fio%</bold><white>!"
    chat: "<#78ff9e>[✔] Успешная регистрация."