name: MFIO
version: '${project.version}'
main: pr.lofe.crp.mfio.MFIO
api-version: '1.20'
description: 'Private plugin for Character RolePlay'
author: 'just_l0fe'
website: 'https://t.me/just_lofe'
permissions:
  admin: {}
  changefio: {}
commands:
  mfio: {}
  changefio: {}